import Head from "next/head";

const Home = () => (
  <div>
    <Head>
      <title>
        News Headlines, Latest News Updates, Today Headlines, Top Stories,
        Breaking News | Nayi Taaza
      </title>
      <meta
        name="description"
        content="News Headlines, Latest News Updates, Today Headlines, Top Stories, Breaking News | Nayi Taaza"
      />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <div className="text-center">
        <h1 className="text-4xl font-bold">Nayi Taaza</h1>
        <p>Stay in touch with what&#39;s happening around</p>
      </div>
    </main>
  </div>
);

export default Home;
