import Head from "next/head";
import Navbar from "../components/Navbar";

const Home = () => (
  <>
    <Head>
      <title>
        News Headlines, Latest News Updates, Today Headlines, Top Stories,
        Breaking News | Nayi Taaza
      </title>
      <meta
        name="description"
        content="News Headlines, Latest News Updates, Today Headlines, Top Stories, Breaking News | Nayi Taaza"
      />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Navbar />
    </main>
  </>
);

export default Home;
